### ISSUE TITLE
GET /my/containers throws 500 when no Authorization header is given

### ISSUE THREAD

**Issue by hayco** [knaw-huc/annorepo#150]
`curl  https://annorepo.republic-caf.diginfra.org/my/containers -H 'accept: application/json'`

->

`{"code":500,"message":"There was an error processing your request. It has been logged (ID 56c7faa3a0be1596)."}`

Expected result: a JSON representation of the containers I'm allowed to use as unauthorized / anonymous user.

**Comment by brambg** [comment]
the `read-only-for-anonymous` container setting was not used in `/my/containers`, I've fixed that.
Do you need this fix in all currently running annorepo instances, or can it wait until the next release?

**Comment by hayco** [comment]
> the `read-only-for-anonymous` container setting was not used in `/my/containers`, I've fixed that. Do you need this fix in all currently running annorepo instances, or can it wait until the next release?

low prio, can wait till next release.
